# Generated by Django 2.2.6 on 2019-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiles_db', '0002_molecule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='calculation',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
