# Generated by Django 2.2.6 on 2019-11-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiles_db', '0003_molecule_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformer',
            name='conformer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conformer',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='calculation',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
