# Generated by Django 2.2.6 on 2019-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiles_db', '0004_auto_20191107_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='cid',
            field=models.IntegerField(default=0),
        ),
    ]
